# Generated by Django 3.1 on 2021-08-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bajaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='john_doe_17091999', editable=False, max_length=150)),
                ('numbers', models.CharField(max_length=266)),
                ('odd', models.CharField(blank=True, max_length=266, null=True)),
                ('even', models.CharField(blank=True, max_length=266, null=True)),
            ],
        ),
    ]
