# Generated by Django 3.1 on 2021-08-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajajapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajaj',
            name='is_success',
            field=models.CharField(default='true', max_length=150),
        ),
    ]
