# Generated by Django 3.1 on 2021-08-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajajapi', '0002_bajaj_is_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajaj',
            name='even',
            field=models.CharField(blank=True, editable=False, max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='bajaj',
            name='is_success',
            field=models.CharField(default='true', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='bajaj',
            name='odd',
            field=models.CharField(blank=True, editable=False, max_length=266, null=True),
        ),
    ]
